services:
  database:
    image: alejandropm205/contenedorbd:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: alejandropm205/contenedorback:latest
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/springboot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

  frontend:
    image: alejandropm205/contenedorfront:latest
    depends_on:
      - backend
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge