services:
  database:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build: ./demo  # Actualiza esta ruta
    container_name: springboot_container
    depends_on:
      - database
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/springboot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

  frontend:
    build: ./php  # Asegúrate de que esta ruta sea correcta
    container_name: php_container
    depends_on:
      - database
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge